name: Build Release Images

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

env:
  BUILD_VERSION: v1.11.4

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Cross Build
        run: |
          docker run --rm -v ${{ github.workspace }}:/go/src/github.com/coredns/coredns \
            -w /go/src/github.com/coredns/coredns \
            ghcr.io/${{ github.repository_owner }}/golang:1.24 \
            bash -c "bash ./.beagle/build.sh"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push images for amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .beagle/dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/coredns:${{ env.BUILD_VERSION }}-amd64
          build-args: |
            BASE=registry.cn-qingdao.aliyuncs.com/wod/alpine:3
            VERSION=${{ env.BUILD_VERSION }}
            TARGETOS=linux
            TARGETARCH=amd64
          provenance: false
          sbom: false

      - name: Build and push images for arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .beagle/dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/coredns:${{ env.BUILD_VERSION }}-arm64
          build-args: |
            BASE=registry.cn-qingdao.aliyuncs.com/wod/alpine:3
            AUTHOR=${{ github.actor }}
            VERSION=${{ env.BUILD_VERSION }}
            TARGETOS=linux
            TARGETARCH=arm64
          provenance: false
          sbom: false

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create registry.cn-qingdao.aliyuncs.com/wod/coredns:${{ env.BUILD_VERSION }} \
            registry.cn-qingdao.aliyuncs.com/wod/coredns:${{ env.BUILD_VERSION }}-amd64 \
            registry.cn-qingdao.aliyuncs.com/wod/coredns:${{ env.BUILD_VERSION }}-arm64
          docker manifest push registry.cn-qingdao.aliyuncs.com/wod/coredns:${{ env.BUILD_VERSION }}
